import type { Reciter, SourceAttribution } from "./types";

export const DEFAULT_RECITER_ID = "ar.alafasy";
export const FRENCH_TRANSLATION_ID = "fr.hamidullah";

export const RECITERS: readonly Reciter[] = [
  { id: "ar.alafasy", name: "Mishary Rashid Alafasy", bitrate: 128 },
] as const;

export const QURAN_SOURCE: SourceAttribution = {
  name: "Al Quran Cloud · Islamic Network CDN",
  url: "https://alquran.cloud",
  termsUrl: "https://alquran.cloud/terms-and-conditions",
};

export const FRENCH_SURAH_NAMES: readonly string[] = [
  "L’ouverture",
  "La Vache",
  "La famille d’Imran",
  "Les Femmes",
  "La Table servie",
  "Les Bestiaux",
  "Al-Araf",
  "Le Butin",
  "Le Repentir",
  "Jonas",
  "Houd",
  "Joseph",
  "Le Tonnerre",
  "Abraham",
  "Al-Hijr",
  "Les Abeilles",
  "Le Voyage nocturne",
  "La Caverne",
  "Marie",
  "Ta-Ha",
  "Les Prophètes",
  "Le Pèlerinage",
  "Les Croyants",
  "La Lumière",
  "Le Discernement",
  "Les Poètes",
  "Les Fourmis",
  "Le Récit",
  "L’Araignée",
  "Les Romains",
  "Luqman",
  "La Prosternation",
  "Les Coalisés",
  "Saba",
  "Le Créateur",
  "Ya-Sin",
  "Les Rangées",
  "Sad",
  "Les Groupes",
  "Le Pardonneur",
  "Les Versets détaillés",
  "La Consultation",
  "L’Ornement",
  "La Fumée",
  "L’Agenouillée",
  "Al-Ahqaf",
  "Muhammad",
  "La Victoire éclatante",
  "Les Appartements",
  "Qaf",
  "Qui éparpillent",
  "Le Mont",
  "L’Étoile",
  "La Lune",
  "Le Tout Miséricordieux",
  "L’Événement",
  "Le Fer",
  "La Discussion",
  "L’Exode",
  "L’Éprouvée",
  "Le Rang",
  "Le Vendredi",
  "Les Hypocrites",
  "La Grande Perte",
  "Le Divorce",
  "L’Interdiction",
  "La Royauté",
  "La Plume",
  "Celle qui montre la vérité",
  "Les Voies d’ascension",
  "Noé",
  "Les Djinns",
  "L’Enveloppé",
  "Le Revêtu d’un manteau",
  "La Résurrection",
  "L’Homme",
  "Les Envoyés",
  "La Nouvelle",
  "Les Anges qui arrachent les âmes",
  "Il s’est renfrogné",
  "L’Obscurcissement",
  "La Rupture",
  "Les Fraudeurs",
  "La Déchirure",
  "Les Constellations",
  "L’Astre nocturne",
  "Le Très-Haut",
  "L’Enveloppante",
  "L’Aube",
  "La Cité",
  "Le Soleil",
  "La Nuit",
  "Le Jour montant",
  "L’Ouverture",
  "Le Figuier",
  "L’Adhérence",
  "La Destinée",
  "La Preuve",
  "La Secousse",
  "Les Coursiers",
  "Le Fracas",
  "La Course aux richesses",
  "Le Temps",
  "Les Calomniateurs",
  "L’Éléphant",
  "Quraysh",
  "L’Ustensile",
  "L’Abondance",
  "Les Infidèles",
  "Les Secours",
  "Les Fibres",
  "Le Monothéisme pur",
  "L’Aube naissante",
  "Les Hommes",
];

export function isAllowedReciter(value: string): value is (typeof RECITERS)[number]["id"] {
  return RECITERS.some((reciter) => reciter.id === value);
}
