import type { CatalogBundle } from "./catalog";

export const SPOKEN_CATALOG: CatalogBundle = {
  sources: [
    {
      id: "source-ia-pickthall",
      name: "Internet Archive — LibriVox / Pickthall",
      originalUrl: "https://archive.org/details/meaning_glorious_koran_0810_librivox",
      publisher: "Internet Archive / LibriVox",
      accessedAt: "2026-09-21",
    },
    {
      id: "source-ia-moors",
      name: "Internet Archive — LibriVox / The Moors in Spain",
      originalUrl: "https://archive.org/details/moorsinspain_1805_librivox",
      publisher: "Internet Archive / LibriVox",
      accessedAt: "2026-09-21",
    },
    {
      id: "source-ia-pilgrimage",
      name: "Internet Archive — LibriVox / Burton pilgrimage",
      originalUrl: "https://archive.org/details/pilgrimage_madinah_meccah_1207_librivox",
      publisher: "Internet Archive / LibriVox",
      accessedAt: "2026-09-21",
    },
    {
      id: "source-ia-ghazali",
      name: "Internet Archive — Kimiya-e-Saadat",
      originalUrl: "https://archive.org/details/Kimiya-e-saadatUrduByImamGhazali",
      publisher: "Internet Archive",
      accessedAt: "2026-09-21",
    },
  ],
  rights: [
    {
      id: "rights-ia-pickthall",
      sourceId: "source-ia-pickthall",
      rightsHolder: "Notice Internet Archive / LibriVox",
      licenseType: "Public Domain Mark",
      licenseVersion: "1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      attributionText: "The Meaning of the Glorious Koran — Mohammed Marmaduke Pickthall; LibriVox recording via Internet Archive.",
      evidenceUrl: "https://archive.org/metadata/meaning_glorious_koran_0810_librivox",
      verifiedAt: "2026-09-21",
      reviewNotes: "Notice et fichier MP3 vérifiés individuellement le 21 septembre 2026. La traduction anglaise et la récitation restent présentées comme une interprétation audio, distincte du texte coranique canonique.",
      verification: "HUMAN_VERIFIED",
      capabilities: { displayMetadata: "YES", embed: "YES", streamRemote: "YES", hostCopy: "NO", downloadOffline: "YES", transcribe: "YES", translate: "YES", createChapters: "YES", createClips: "YES", modify: "YES", commercialUse: "YES" },
    },
    {
      id: "rights-ia-moors",
      sourceId: "source-ia-moors",
      rightsHolder: "Notice Internet Archive / LibriVox",
      licenseType: "Public Domain Mark",
      licenseVersion: "1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      attributionText: "The Moors in Spain — Stanley Lane-Poole; LibriVox recording via Internet Archive.",
      evidenceUrl: "https://archive.org/metadata/moorsinspain_1805_librivox",
      verifiedAt: "2026-09-21",
      reviewNotes: "Notice, page LibriVox et fichier MP3 vérifiés individuellement le 21 septembre 2026. Contenu historique, présenté comme tel et non comme un avis religieux.",
      verification: "HUMAN_VERIFIED",
      capabilities: { displayMetadata: "YES", embed: "YES", streamRemote: "YES", hostCopy: "NO", downloadOffline: "YES", transcribe: "YES", translate: "YES", createChapters: "YES", createClips: "YES", modify: "YES", commercialUse: "YES" },
    },
    {
      id: "rights-ia-pilgrimage",
      sourceId: "source-ia-pilgrimage",
      rightsHolder: "Notice Internet Archive / LibriVox",
      licenseType: "CC0",
      licenseVersion: "1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      attributionText: "Personal Narrative of a Pilgrimage to Al-Madinah and Meccah — Richard Francis Burton; LibriVox recording via Internet Archive.",
      evidenceUrl: "https://archive.org/metadata/pilgrimage_madinah_meccah_1207_librivox",
      verifiedAt: "2026-09-21",
      reviewNotes: "Notice, page LibriVox et fichier MP3 vérifiés individuellement le 21 septembre 2026. Récit historique de voyage, sans validation éditoriale de ses interprétations.",
      verification: "HUMAN_VERIFIED",
      capabilities: { displayMetadata: "YES", embed: "YES", streamRemote: "YES", hostCopy: "NO", downloadOffline: "YES", transcribe: "YES", translate: "YES", createChapters: "YES", createClips: "YES", modify: "YES", commercialUse: "YES" },
    },
    {
      id: "rights-ia-ghazali",
      sourceId: "source-ia-ghazali",
      rightsHolder: "Notice Internet Archive",
      licenseType: "CC0",
      licenseVersion: "1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      attributionText: "Kimiya-e-Saadat Urdu — Imam Ghazali; audio file via Internet Archive.",
      evidenceUrl: "https://archive.org/metadata/Kimiya-e-saadatUrduByImamGhazali",
      verifiedAt: "2026-09-21",
      reviewNotes: "Notice et fichier MP3 vérifiés individuellement le 21 septembre 2026. L'audio est en ourdou et le catalogue ne prétend pas fournir une traduction française.",
      verification: "HUMAN_VERIFIED",
      capabilities: { displayMetadata: "YES", embed: "YES", streamRemote: "YES", hostCopy: "NO", downloadOffline: "YES", transcribe: "YES", translate: "YES", createChapters: "YES", createClips: "YES", modify: "YES", commercialUse: "YES" },
    },
  ],
  topics: [
    { id: "topic-quran-translation", slug: "quran-translation", label: "Traduction du Coran" },
    { id: "topic-islamic-history", slug: "islamic-history", label: "Histoire islamique" },
    { id: "topic-pilgrimage", slug: "pilgrimage", label: "Pèlerinage" },
    { id: "topic-spirituality", slug: "spirituality", label: "Spiritualité" },
  ],
  creators: [
    { id: "creator-pickthall", slug: "marmaduke-pickthall", name: "Mohammed Marmaduke Pickthall", languages: ["en"], roles: ["AUTHOR"], officialUrls: [] },
    { id: "creator-lane-poole", slug: "stanley-lane-poole", name: "Stanley Lane-Poole", languages: ["en"], roles: ["AUTHOR"], officialUrls: [] },
    { id: "creator-burton", slug: "richard-francis-burton", name: "Richard Francis Burton", languages: ["en"], roles: ["AUTHOR"], officialUrls: [] },
    { id: "creator-ghazali", slug: "imam-ghazali", name: "Imam Ghazali", languages: ["ar", "ur"], roles: ["AUTHOR"], officialUrls: [] },
    { id: "creator-librivox", slug: "librivox", name: "LibriVox", languages: ["en"], roles: ["ORGANIZATION"], officialUrls: ["https://librivox.org/"] },
  ],
  series: [
    {
      id: "series-islamic-heritage-audio",
      slug: "islamic-heritage-audio",
      title: "Patrimoine islamique — audio libre",
      description: "Une sélection de documents audio dont la notice source déclare la réutilisabilité.",
      creatorIds: ["creator-librivox"],
      orderedContentIds: ["spoken-pickthall-al-fatiha", "spoken-moors-spain-chapter-1", "spoken-pilgrimage-chapter-1", "spoken-ghazali-introduction"],
    },
  ],
  media: [
    {
      id: "media-pickthall-al-fatiha",
      kind: "AUDIO",
      url: "https://archive.org/download/meaning_glorious_koran_0810_librivox/koran_01_pickthall.mp3",
      durationMs: 57490,
      sourceId: "source-ia-pickthall",
      rightsRecordId: "rights-ia-pickthall",
      mimeType: "audio/mpeg",
      sizeBytes: 919854,
      checksumSha1: "064fb68e11c83cd64aa04832b69ac9bf30f08eb3",
      sourceFileName: "koran_01_pickthall.mp3",
      variantIds: ["variant-pickthall-standard"],
    },
    {
      id: "media-moors-spain-chapter-1",
      kind: "AUDIO",
      url: "https://archive.org/download/moorsinspain_1805_librivox/moorsinspain_01_lane-poole_128kb.mp3",
      durationMs: 1934160,
      sourceId: "source-ia-moors",
      rightsRecordId: "rights-ia-moors",
      mimeType: "audio/mpeg",
      sizeBytes: 30951220,
      checksumSha1: "097e8840579ae390d4345902bcb637635865cdee",
      sourceFileName: "moorsinspain_01_lane-poole_128kb.mp3",
      variantIds: ["variant-moors-standard"],
    },
    {
      id: "media-pilgrimage-chapter-1",
      kind: "AUDIO",
      url: "https://archive.org/download/pilgrimage_madinah_meccah_1207_librivox/pilgrimage_01_burton.mp3",
      durationMs: 405020,
      sourceId: "source-ia-pilgrimage",
      rightsRecordId: "rights-ia-pilgrimage",
      mimeType: "audio/mpeg",
      sizeBytes: 6482254,
      checksumSha1: "89681e60edc75d5803f8cb10a894620a17f9da7e",
      sourceFileName: "pilgrimage_01_burton.mp3",
      variantIds: ["variant-pilgrimage-standard"],
    },
    {
      id: "media-ghazali-introduction",
      kind: "AUDIO",
      url: "https://archive.org/download/Kimiya-e-saadatUrduByImamGhazali/02-ImamGhazalisIntroduction-RealSuccessDependentOnMaarifa-proximityOfGodAndIbadah-worship.mp3",
      durationMs: 1017280,
      sourceId: "source-ia-ghazali",
      rightsRecordId: "rights-ia-ghazali",
      mimeType: "audio/mpeg",
      sizeBytes: 8138292,
      checksumSha1: "3c0f7d14570cee96fccb6d2b1aa6b49ac58f1d99",
      sourceFileName: "02-ImamGhazalisIntroduction-RealSuccessDependentOnMaarifa-proximityOfGodAndIbadah-worship.mp3",
      variantIds: ["variant-ghazali-standard"],
    },
  ],
  contents: [
    {
      id: "spoken-pickthall-al-fatiha",
      slug: "pickthall-al-fatiha-audio",
      type: "AUDIOBOOK",
      title: "Le sens du Glorieux Coran — Al-Fātiḥa",
      description: "Premier fichier audio de la traduction anglaise de Mohammed Marmaduke Pickthall, lue dans le cadre d'une production LibriVox.",
      language: "en",
      level: "BEGINNER",
      status: "PUBLISHED",
      creatorIds: ["creator-pickthall", "creator-librivox"],
      topicIds: ["topic-quran-translation"],
      seriesId: "series-islamic-heritage-audio",
      mediaAssetIds: ["media-pickthall-al-fatiha"],
      sourceId: "source-ia-pickthall",
      artworkUrl: "https://archive.org/services/img/meaning_glorious_koran_0810_librivox",
      artworkAlt: "Notice audio LibriVox du sens du Glorieux Coran",
      publishedAt: "2026-09-21",
    },
    {
      id: "spoken-moors-spain-chapter-1",
      slug: "moors-in-spain-chapter-1",
      type: "AUDIOBOOK",
      title: "The Moors in Spain — chapitre 1",
      description: "Premier chapitre du récit historique de Stanley Lane-Poole, enregistré par LibriVox.",
      language: "en",
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      creatorIds: ["creator-lane-poole", "creator-librivox"],
      topicIds: ["topic-islamic-history"],
      seriesId: "series-islamic-heritage-audio",
      mediaAssetIds: ["media-moors-spain-chapter-1"],
      sourceId: "source-ia-moors",
      artworkUrl: "https://archive.org/services/img/moorsinspain_1805_librivox",
      artworkAlt: "Notice audio LibriVox de The Moors in Spain",
      publishedAt: "2026-09-21",
    },
    {
      id: "spoken-pilgrimage-chapter-1",
      slug: "pilgrimage-madinah-meccah-chapter-1",
      type: "AUDIOBOOK",
      title: "Personal Narrative of a Pilgrimage — chapitre 1",
      description: "Premier chapitre du récit de voyage de Richard Francis Burton vers Al-Madinah et La Mecque, enregistré par LibriVox.",
      language: "en",
      level: "INTERMEDIATE",
      status: "PUBLISHED",
      creatorIds: ["creator-burton", "creator-librivox"],
      topicIds: ["topic-pilgrimage"],
      seriesId: "series-islamic-heritage-audio",
      mediaAssetIds: ["media-pilgrimage-chapter-1"],
      sourceId: "source-ia-pilgrimage",
      artworkUrl: "https://archive.org/services/img/pilgrimage_madinah_meccah_1207_librivox",
      artworkAlt: "Notice audio LibriVox du récit de pèlerinage",
      publishedAt: "2026-09-21",
    },
    {
      id: "spoken-ghazali-introduction",
      slug: "ghazali-kimiya-saadat-introduction",
      type: "AUDIOBOOK",
      title: "Kimiya-e-Saadat — introduction",
      description: "Introduction en ourdou à l'audio du traité spirituel attribué à Imam Ghazali.",
      language: "ur",
      level: "ADVANCED",
      status: "PUBLISHED",
      creatorIds: ["creator-ghazali"],
      topicIds: ["topic-spirituality"],
      seriesId: "series-islamic-heritage-audio",
      mediaAssetIds: ["media-ghazali-introduction"],
      sourceId: "source-ia-ghazali",
      artworkUrl: "https://archive.org/services/img/Kimiya-e-saadatUrduByImamGhazali",
      artworkAlt: "Notice audio de Kimiya-e-Saadat",
      publishedAt: "2026-09-21",
    },
  ],
  collections: [
    {
      id: "collection-public-domain-islamic-heritage",
      slug: "public-domain-islamic-heritage",
      title: "Patrimoine islamique — sources libres",
      description: "Contenus audio publiés uniquement avec une notice de source et une décision de droits vérifiée.",
      curatorName: "RIHLA",
      topicIds: ["topic-quran-translation", "topic-islamic-history", "topic-pilgrimage", "topic-spirituality"],
      contentIds: ["spoken-pickthall-al-fatiha", "spoken-moors-spain-chapter-1", "spoken-pilgrimage-chapter-1", "spoken-ghazali-introduction"],
    },
  ],
  chapters: [
    { id: "chapter-pickthall-al-fatiha", contentId: "spoken-pickthall-al-fatiha", title: "Al-Fātiḥa", startMs: 0, endMs: 57490, position: 1 },
    { id: "chapter-moors-spain-1", contentId: "spoken-moors-spain-chapter-1", title: "Chapitre 1", startMs: 0, endMs: 1934160, position: 1 },
    { id: "chapter-pilgrimage-1", contentId: "spoken-pilgrimage-chapter-1", title: "Chapitre 1", startMs: 0, endMs: 405020, position: 1 },
    { id: "chapter-ghazali-introduction", contentId: "spoken-ghazali-introduction", title: "Introduction", startMs: 0, endMs: 1017280, position: 1 },
  ],
  variants: [
    { id: "variant-pickthall-standard", mediaAssetId: "media-pickthall-al-fatiha", kind: "AUDIO", url: "https://archive.org/download/meaning_glorious_koran_0810_librivox/koran_01_pickthall.mp3", quality: "STANDARD", mimeType: "audio/mpeg", sizeBytes: 919854, checksumSha1: "064fb68e11c83cd64aa04832b69ac9bf30f08eb3" },
    { id: "variant-moors-standard", mediaAssetId: "media-moors-spain-chapter-1", kind: "AUDIO", url: "https://archive.org/download/moorsinspain_1805_librivox/moorsinspain_01_lane-poole_128kb.mp3", quality: "STANDARD", mimeType: "audio/mpeg", sizeBytes: 30951220, checksumSha1: "097e8840579ae390d4345902bcb637635865cdee" },
    { id: "variant-pilgrimage-standard", mediaAssetId: "media-pilgrimage-chapter-1", kind: "AUDIO", url: "https://archive.org/download/pilgrimage_madinah_meccah_1207_librivox/pilgrimage_01_burton.mp3", quality: "STANDARD", mimeType: "audio/mpeg", sizeBytes: 6482254, checksumSha1: "89681e60edc75d5803f8cb10a894620a17f9da7e" },
    { id: "variant-ghazali-standard", mediaAssetId: "media-ghazali-introduction", kind: "AUDIO", url: "https://archive.org/download/Kimiya-e-saadatUrduByImamGhazali/02-ImamGhazalisIntroduction-RealSuccessDependentOnMaarifa-proximityOfGodAndIbadah-worship.mp3", quality: "STANDARD", mimeType: "audio/mpeg", sizeBytes: 8138292, checksumSha1: "3c0f7d14570cee96fccb6d2b1aa6b49ac58f1d99" },
  ],
  transcripts: [],
  transcriptSegments: [],
};
